import { CulturalTrivia } from "../types";

// 100 questions spread across: Regions, Religion, Identity, History, Culture, Norms, Geography, Language, Festivals, Food
const RAW_TRIVIA_POOL: CulturalTrivia[] = [
  // === HISTORY ===
  { question: "Who led Ethiopia to victory at the Battle of Adwa in 1896?", answer: "Emperor Menelik II", explanation: "Emperor Menelik II and Empress Taytu Betul commanded Ethiopia's forces against Italy, making Adwa the first decisive African victory over a European colonial army." },
  { question: "What ancient empire built towering granite obelisks in northern Ethiopia?", answer: "The Axumite Empire", explanation: "The Kingdom of Axum, one of the greatest civilizations of the ancient world, erected massive stone obelisks (stelae) as royal funerary monuments in modern-day Tigray." },
  { question: "Which Ethiopian emperor ended the 'Era of the Princes' in 1855?", answer: "Emperor Tewodros II", explanation: "Tewodros II reunified a fragmented Ethiopia after the chaotic Zemene Mesafint period, laying the groundwork for the modern Ethiopian state." },
  { question: "In what year did Emperor Haile Selassie first address the League of Nations?", answer: "1936", explanation: "After the Italian invasion, Haile Selassie became the first head of state to personally address the League of Nations in Geneva, urging collective security." },
  { question: "What dynasty ruled Ethiopia from the 13th century until 1974?", answer: "The Solomonic Dynasty", explanation: "The Solomonic Dynasty claimed descent from King Solomon and the Queen of Sheba. It ruled Ethiopia for centuries until Emperor Haile Selassie was deposed by the Derg." },
  { question: "What was the name of the military communist junta that ruled Ethiopia from 1974 to 1991?", answer: "The Derg", explanation: "The Derg (meaning 'committee' in Ge'ez) overthrew Emperor Haile Selassie in 1974 and ruled under a socialist military dictatorship until it was ousted in 1991." },
  { question: "Who was the first Muslim refugee-welcoming king of the Axumite Empire?", answer: "King Armah (Al-Nejashi)", explanation: "In 615 AD, King Armah welcomed the early companions of Prophet Muhammad fleeing persecution, establishing a historic bond of tolerance between Ethiopia and Islam." },
  { question: "When was the Grand Ethiopian Renaissance Dam completed for first filling?", answer: "July 2020", explanation: "The GERD began its first water reservoir filling in July 2020. It is Africa's largest hydroelectric dam, built on the Blue Nile in Benishangul-Gumuz region." },
  { question: "Which Ethiopian queen is said to have brought gold and spices to King Solomon?", answer: "Queen of Sheba (Makeda)", explanation: "Ethiopian tradition holds that Queen Makeda (Queen of Sheba) visited King Solomon of Jerusalem, and their union produced Menelik I, founder of the Solomonic dynasty." },
  { question: "In which century were the rock-hewn churches of Lalibela built?", answer: "12th century (c. 1200 AD)", explanation: "King Gebre Mesqel Lalibela of the Zagwe dynasty commissioned 11 monolithic churches carved from solid red volcanic rock, intended as a 'New Jerusalem' in Africa." },

  // === RELIGION ===
  { question: "What is the largest religious denomination in Ethiopia?", answer: "Ethiopian Orthodox Tewahedo Church", explanation: "The Ethiopian Orthodox Church is one of the oldest Christian churches in the world, founded in the 4th century. It has a unique canon including 81 books in its Bible." },
  { question: "What is the second largest religion in Ethiopia?", answer: "Islam", explanation: "Islam is practiced by approximately 34-35% of Ethiopians, particularly in the Somali, Afar, Harari, and parts of Oromia regions." },
  { question: "What is Ethiopia's ancient Christian celebration of Epiphany called?", answer: "Timkat", explanation: "Timkat (ጥምቀት) is celebrated on January 19 and commemorates the baptism of Jesus in the Jordan River. Priests carry the Tabot (Ark replica) in a solemn procession." },
  { question: "Which city in Ethiopia is considered one of the holiest cities in Islam?", answer: "Harar (Jugol)", explanation: "Harar is sometimes called the fourth holiest city in Islam by its residents. It contains over 82 mosques within its ancient walled city and was a major Islamic scholarly center." },
  { question: "What is the name of the Ethiopian Christian fasting period before Easter?", answer: "Tsome Filseta (Great Fast / Abiy Tsom)", explanation: "Ethiopian Orthodox Christians observe one of the longest fasting periods in the world — up to 55 days before Fasika (Easter) — eating only vegan food after 3 PM each day." },
  { question: "What sacred object is the Ethiopian Orthodox Church believed to possess in Axum?", answer: "The Ark of the Covenant", explanation: "The Church of Our Lady Mary of Zion in Axum claims to house the original Ark of the Covenant, guarded by a single monk. It is one of the most revered claims in Christian history." },
  { question: "What is the name of the feast celebrating the finding of the True Cross in Ethiopia?", answer: "Meskel", explanation: "Meskel (September 27) is a major Ethiopian Orthodox holiday marked by a large bonfire called Demera. UNESCO recognized it as an Intangible Cultural Heritage in 2013." },
  { question: "What is the Muslim holiday of fasting observed in Ethiopia called?", answer: "Ramadan (Himamat)", explanation: "Ethiopian Muslims observe Ramadan, fasting from dawn to sunset. The breaking of fast (Iftar) is celebrated communally, especially in cities like Harar, Dire Dawa, and Addis Ababa." },
  { question: "What is the Jewish minority community in Ethiopia called?", answer: "Beta Israel (Falasha)", explanation: "Beta Israel are Ethiopian Jews who practiced a form of Judaism based on the Torah and Ge'ez texts. Many emigrated to Israel through Operations Moses and Solomon." },
  { question: "What does 'Tewahedo' mean in the Ethiopian Orthodox Church name?", answer: "Made One (Unity)", explanation: "'Tewahedo' (ተዋሕዶ) means 'being made one' and refers to the church's miaphysite theology — the belief that Christ has one united divine-human nature." },

  // === REGIONS ===
  { question: "Which is the largest regional state in Ethiopia by area?", answer: "Oromia", explanation: "Oromia is the largest regional state in Ethiopia, home to the Oromo people — the country's largest ethnic group. Its capital is Addis Ababa (shared with the federal government)." },
  { question: "Which Ethiopian region is known as the 'cradle of coffee'?", answer: "Kaffa (Kefa) Zone, SWEPRS", explanation: "The Kaffa zone in southwest Ethiopia is the wild birthplace of Arabica coffee. Coffee forests there are UNESCO-recognized Biosphere Reserves." },
  { question: "Which region of Ethiopia is home to the Danakil Depression?", answer: "Afar Region", explanation: "The Afar region contains the Danakil Depression, one of the lowest and hottest places on Earth. It is also where Lucy (Dinknesh) was discovered in 1974." },
  { question: "What is the capital city of the Tigray region?", answer: "Mekelle", explanation: "Mekelle is the capital of the Tigray region in northern Ethiopia. It is a major economic hub and gateway to the ancient city of Axum and Lalibela." },
  { question: "Which region is the Simien Mountains National Park located in?", answer: "Amhara Region", explanation: "The Simien Mountains, a UNESCO World Heritage Site, are located in the Amhara region. They are home to the rare Gelada baboon, Ethiopian wolf, and Walia ibex." },
  { question: "What is the capital of the Oromia regional state?", answer: "Addis Ababa", explanation: "Addis Ababa serves as the capital of both the Federal Government of Ethiopia and the Oromia regional state, making it politically significant for both." },
  { question: "Which Ethiopian region borders Kenya and South Sudan?", answer: "Gambella Region", explanation: "Gambella, in southwest Ethiopia, borders both Kenya and South Sudan. It is home to the Anuak, Nuer, and Majangir peoples and contains unique tropical biodiversity." },
  { question: "What is the only city in Ethiopia with a UNESCO World Heritage walled old city?", answer: "Harar", explanation: "Harar Jugol, the walled city of Harar in the Harari region, is a UNESCO World Heritage Site recognized for its 82+ mosques and unique Islamic architectural heritage." },
  { question: "Which Ethiopian region is home to the Omo Valley and its ancient tribal communities?", answer: "South Ethiopia Region (formerly SNNPR)", explanation: "The Omo Valley in southern Ethiopia is a UNESCO World Heritage Site and home to dozens of ancient tribal communities including the Mursi, Hamer, Banna, and Karo peoples." },
  { question: "What is the name of the smallest regional state in Ethiopia by population?", answer: "Harari Region", explanation: "The Harari Region is the smallest regional state in Ethiopia by population, centered entirely around the historic walled city of Harar." },

  // === IDENTITY & ETHNIC GROUPS ===
  { question: "What is the largest ethnic group in Ethiopia?", answer: "The Oromo", explanation: "The Oromo make up approximately 35-40% of Ethiopia's population and are spread across the large Oromia region as well as parts of other regions." },
  { question: "What is the traditional thanksgiving festival of the Oromo people?", answer: "Irreechaa", explanation: "Irreechaa is the Oromo harvest thanksgiving festival celebrated at the shores of sacred lakes (primarily Lake Hora Arsadi near Bishoftu) in September. Millions attend." },
  { question: "What is the Afar people's traditional nomadic lifestyle centered around?", answer: "Camel and goat herding", explanation: "The Afar people are traditionally nomadic pastoralists in the harsh desert lowlands of the Afar region, relying on camels, goats, and cattle." },
  { question: "What is the traditional Sidama house called?", answer: "Sidama Darboo (Waga)", explanation: "The Sidama people of southern Ethiopia build unique cylindrical thatched houses called Darboo. The Sidama region became Ethiopia's 10th regional state in 2020." },
  { question: "What is the name of the Tigrinya-speaking people of northern Ethiopia?", answer: "Tigrayans (Tigrayan people)", explanation: "The Tigrinya-speaking Tigrayan people of northern Ethiopia are historically linked to the ancient Axumite civilization and make up about 6% of Ethiopia's population." },
  { question: "What are the Somali people of Ethiopia primarily concentrated in?", answer: "The Somali Region (Ogaden)", explanation: "The Somali Regional State in eastern Ethiopia is predominantly inhabited by ethnic Somalis who are largely Muslim and have a strong nomadic pastoral tradition." },
  { question: "What ethnic group is associated with the Eskista dance tradition?", answer: "The Amhara people", explanation: "Eskista, characterized by rolling shoulders and bouncing chest movements, is most closely associated with the Amhara people, though it is now enjoyed across all of Ethiopia." },
  { question: "What is the Hamer people of southern Ethiopia famous for?", answer: "The Bull Jumping ceremony", explanation: "The Hamer people perform a dramatic coming-of-age ritual called Bull Jumping, where a young man must run across the backs of a line of cattle to prove his readiness for marriage." },
  { question: "What is the Mursi tribe in the Omo Valley known for?", answer: "Lip plates worn by women", explanation: "Mursi women traditionally insert large clay or wooden plates into their lower lips as a sign of identity and beauty. This practice is unique to the Mursi and nearby Suri people." },
  { question: "What group of people historically practiced the Gadaa system?", answer: "The Oromo people", explanation: "The Gadaa system is the ancient democratic governance structure of the Oromo, organizing society into age-grade classes that rotate political power every 8 years." },

  // === GEOGRAPHY & CLIMATE ===
  { question: "What is the highest mountain in Ethiopia?", answer: "Ras Dashen (4,550m)", explanation: "Ras Dashen in the Simien Mountains of the Amhara region is the highest peak in Ethiopia at 4,550 meters and the 10th highest in Africa." },
  { question: "Which major river originates in Ethiopia and flows into Egypt?", answer: "The Blue Nile (Abbay)", explanation: "The Blue Nile, known locally as Abbay, originates at Lake Tana in the Amhara region and provides about 85% of the total water flow of the Nile River into Egypt." },
  { question: "What is the largest lake in Ethiopia?", answer: "Lake Tana", explanation: "Lake Tana in the Amhara region is the source of the Blue Nile. It contains 37 islands with ancient monasteries dating back to the 14th century." },
  { question: "Which geological feature divides Ethiopia into highlands and lowlands?", answer: "The Great Rift Valley", explanation: "The East African Great Rift Valley cuts through Ethiopia, creating a dramatic landscape of volcanic lakes, escarpments, and rich biodiversity corridors." },
  { question: "How many UNESCO World Heritage Sites does Ethiopia have?", answer: "9 sites", explanation: "Ethiopia has 9 UNESCO World Heritage Sites including Lalibela, Axum, Harar Jugol, Simien Mountains, Fasil Ghebbi (Gondar), Lower Valley of the Awash (Lucy site), and more." },
  { question: "What is the name of Ethiopia's active volcano and lava lake in Afar?", answer: "Erta Ale", explanation: "Erta Ale (meaning 'smoking mountain' in Afar) is one of the world's few continuously active lava lake volcanoes, located in the Danakil Depression in the Afar region." },
  { question: "What is the Ethiopian Highlands often called internationally?", answer: "The Roof of Africa", explanation: "Due to its massive high-altitude plateau averaging over 2,000 meters, Ethiopia's highlands are commonly called the 'Roof of Africa'." },
  { question: "Lake Langano is a popular resort lake located in which Ethiopian region?", answer: "Oromia Region", explanation: "Lake Langano, one of the few bilharzia-free lakes in Ethiopia, is a popular vacation destination for Addis Ababa residents, located south of the capital in Oromia." },
  { question: "Which Ethiopian city is the gateway to the Bale Mountains National Park?", answer: "Robe (Goba)", explanation: "The town of Robe (Goba) in Oromia is the gateway to Bale Mountains National Park, home to the Ethiopian wolf — the world's rarest canid." },

  // === LANGUAGE & SCRIPT ===
  { question: "What is the official working language of the Ethiopian federal government?", answer: "Amharic", explanation: "Amharic (አማርኛ) is the official working language of the Ethiopian federal government. It is a Semitic language and the second most spoken Semitic language in the world after Arabic." },
  { question: "How many letters does the Ge'ez (Ethiopic) script have in its basic form?", answer: "33 base characters (with 7 orders = 231 syllables)", explanation: "The Ge'ez abugida has 33 consonant base characters, each modified in 7 ways for different vowel sounds, producing 231 distinct syllabic characters." },
  { question: "What language family does Afaan Oromoo belong to?", answer: "Cushitic (Afroasiatic) family", explanation: "Afaan Oromoo (Oromo language) belongs to the Cushitic branch of the Afroasiatic language family. It is the most widely spoken Cushitic language in the world." },
  { question: "What is the ancient liturgical language of the Ethiopian Orthodox Church?", answer: "Ge'ez (Classical Ethiopic)", explanation: "Ge'ez is the ancient Semitic language of the Axumite Empire. Though no longer spoken as a mother tongue, it remains the sacred liturgical language of the Ethiopian Orthodox Church." },
  { question: "In which script is Afaan Oromoo officially written today?", answer: "Qubee (Latin-based alphabet)", explanation: "Afaan Oromoo officially uses Qubee, a Latin-based orthography adopted in the 1990s. Before that, it was written in Ge'ez script or Arabic in some regions." },

  // === FOOD & CUISINE ===
  { question: "What is the national dish of Ethiopia?", answer: "Doro Wat with Injera", explanation: "Doro Wat is a rich, spicy chicken stew made with berbere spice and boiled eggs. It is served on Injera and eaten communally, especially at celebrations and holidays." },
  { question: "What spice blend is the backbone of most Ethiopian stews?", answer: "Berbere", explanation: "Berbere is a complex blend of chili peppers, fenugreek, coriander, korarima, rue, ajwain, and other spices. It gives Ethiopian stews their signature deep-red color and rich flavor." },
  { question: "What is the Ethiopian act of feeding food directly into someone else's mouth called?", answer: "Gursha", explanation: "Gursha is the Ethiopian tradition of placing food into the mouth of another person as an act of deep friendship, love, and communal bonding. It is considered a great honor." },
  { question: "What is the fermented grain starter used to make Injera called?", answer: "Ersho", explanation: "Ersho is the natural liquid yeast starter saved from previous Injera batches, mixed with teff flour and water, then fermented for 2-4 days before baking." },
  { question: "What is the Ethiopian spiced butter used in cooking called?", answer: "Niter Kibbeh", explanation: "Niter Kibbeh is a clarified spiced butter infused with onions, garlic, ginger, korarima, turmeric, and other spices. It is the foundational cooking fat of Ethiopian cuisine." },
  { question: "What is the raw minced meat dish in Ethiopian cuisine called?", answer: "Kitfo (Kifto)", explanation: "Kitfo is a traditional Ethiopian dish of minced raw beef seasoned with Mitmita (bird's eye chili) and Niter Kibbeh. It is considered a delicacy, especially among the Gurage people." },
  { question: "What is the traditional round woven basket table used to serve Ethiopian food?", answer: "Mesob", explanation: "The Mesob is a tall, colorfully woven basket-table used to serve Injera and Wat. It is handcrafted by women and serves as both functional furniture and decorative art." },
  { question: "What is the Ethiopian Christmas holiday called?", answer: "Genna (Leddet)", explanation: "Genna (January 7) is the Ethiopian Orthodox Christmas. It is celebrated with church services, a traditional stick game also called Genna, and a communal feast after a long fast." },

  // === CULTURE & NORMS ===
  { question: "What is the traditional Ethiopian greeting when entering someone's home?", answer: "Selam (ሰላም) — Peace", explanation: "Selam means peace in Amharic and Ge'ez and is the standard greeting. It is often accompanied by a bow, handshake, or cheek-kiss depending on the region and relationship." },
  { question: "What is the Ethiopian coffee ceremony called in Amharic?", answer: "Bunna Ceremony (ቡና ጠጅ)", explanation: "The Buna ceremony involves roasting green coffee beans over coals, grinding them by hand, and brewing three rounds called Abol, Tona, and Baraka — each with symbolic meaning." },
  { question: "What is the cultural norm of communal eating in Ethiopia called?", answer: "Eating from a shared platter", explanation: "Ethiopians traditionally eat from a single large communal platter of Injera without individual plates. This reinforces community, equality, and togetherness." },
  { question: "What is the traditional Amhara formal dress for women called?", answer: "Habesha Kemis (ሐበሻ ቀሚስ)", explanation: "The Habesha Kemis is a traditional white cotton dress with colorful embroidered borders (Tibeb), worn by Ethiopian and Eritrean women at festivals and celebrations." },
  { question: "What is the traditional Oromo male dress of honor called?", answer: "Simbirro and Garaacha", explanation: "Traditional Oromo men wear leather garments and carry a Bokkuu (scepter) during Gadaa ceremonies. The Garaacha is a distinctive shawl worn by elders." },
  { question: "What does it mean to receive a coffee cup with both hands in Ethiopia?", answer: "It is a sign of respect", explanation: "Receiving the small coffee cup (Cini) with both hands, or with the right hand supported by the left, is a traditional gesture of respect and gratitude throughout Ethiopia." },
  { question: "Which of Ethiopia's 9 UNESCO sites is known for medieval African castles?", answer: "Fasil Ghebbi (Royal Enclosure of Gondar)", explanation: "Fasil Ghebbi in Gondar, Amhara region, is a UNESCO World Heritage Site featuring stone castles built by Emperor Fasilides and his successors in the 17th-18th centuries." },
  { question: "What is the Amhara traditional shoulder dance called?", answer: "Eskista (እስኪስታ)", explanation: "Eskista is a vigorous traditional dance unique to the highlands of Ethiopia, featuring rolling and bouncing shoulder and chest movements performed at weddings and celebrations." },
  { question: "What is the Somali region's traditional nomadic tent home called?", answer: "Aqal (Xeedho)", explanation: "The Aqal (or Xeedho) is a portable dome-shaped tent made from bent sticks and covered with woven mats and animal skins. It can be assembled and disassembled in hours for nomadic travel." },
  { question: "What is the traditional Afar blade weapon used in ceremonies?", answer: "Jile knife", explanation: "The Jile is a traditional curved dagger used by Afar men. It is worn on the hip and symbolizes manhood, courage, and identity in Afar culture." },

  // === FESTIVALS ===
  { question: "What is the Oromo harvest thanksgiving ceremony celebrated near Lake Hora called?", answer: "Irreechaa", explanation: "Irreechaa is the Oromo festival of thanksgiving to Waaqayyo (God) for the end of the rainy season. Millions gather at Lake Hora Arsadi in Bishoftu each October." },
  { question: "What is the Ethiopian Orthodox feast celebrating Mary's Assumption called?", answer: "Filseta (Mariam's Assumption)", explanation: "Filseta (August 22) celebrates the Assumption of the Virgin Mary. It follows a 15-day fast and is one of the most important Marian feasts in the Ethiopian Orthodox calendar." },
  { question: "What is the Rastafari connection to Ethiopia?", answer: "Emperor Haile Selassie is revered as God incarnate (Jah)", explanation: "The Rastafari movement, founded in Jamaica in the 1930s, reveres Emperor Haile Selassie I as the returned Messiah. Ethiopia, Zion, and the Ethiopian flag colors are central to Rastafari identity." },
  { question: "Which Ethiopian festival involves a bonfire called Demera?", answer: "Meskel", explanation: "During Meskel, a towering bonfire called Demera is lit in town squares. The direction it falls is believed to predict future fortunes. It is celebrated on September 27." },
  { question: "What is the Ethiopian New Year flower called?", answer: "Adey Abeba (Meskel flower)", explanation: "The bright yellow Adey Abeba (Bidens macroptera) blooms across the highlands at the end of the rainy season. It symbolizes the Ethiopian New Year (Enkutatash) on September 11." },

  // === SCIENCE & INNOVATION ===
  { question: "What is the local Amharic name for the Ethiopian 3.2-million-year-old fossil 'Lucy'?", answer: "Dinknesh (ድንቅነሽ)", explanation: "'Dinknesh' means 'you are wonderful' or 'you are marvelous' in Amharic. The name reflects the profound national pride Ethiopians feel about the discovery." },
  { question: "What is the name of Ethiopia's space science and technology agency?", answer: "Ethiopian Space Science and Technology Institute (ESSTI)", explanation: "Ethiopia established ESSTI with the vision of being a space-faring nation. The institute operates observatories and satellite programs as part of the national science agenda." },
  { question: "What was the first satellite launched by Ethiopia?", answer: "ETRSS-1 (2019)", explanation: "Ethiopia launched its first satellite, ETRSS-1, in December 2019 from China. It was a remote sensing satellite designed to monitor agriculture, water resources, and weather." },
  { question: "What ancient grain native to Ethiopia is considered a modern superfood?", answer: "Teff", explanation: "Teff (Eragrostis tef) is an ancient grain domesticated in Ethiopia over 3,000 years ago. It is gluten-free, high in iron, calcium, and protein, making it popular worldwide." },

  // === NATIONAL IDENTITY ===
  { question: "What does the star on the Ethiopian flag represent?", answer: "Unity of all Ethiopian peoples", explanation: "The blue circle and golden star with rays on the Ethiopian flag represent the unity of all nationalities and peoples of Ethiopia and the bright future of the country." },
  { question: "What does the word 'Ethiopia' mean in Greek?", answer: "Land of the Burnt Faces (Aithiops)", explanation: "The ancient Greek term 'Aithiops' (Αἰθίοψ) means 'burned face' or 'sun-burned face', used broadly for dark-skinned peoples south of Egypt. It later became the name for the nation." },
  { question: "What country is Ethiopia the oldest ally of, dating back to 615 AD?", answer: "The Muslim world (particularly Saudi Arabia / Hejaz)", explanation: "Since King Armah sheltered the companions of Prophet Muhammad in 615 AD, Ethiopia has been recognized as a land of justice in Islamic tradition, creating an early bond with the Muslim world." },
  { question: "What is the motto of Ethiopia?", answer: "Ethiopia Prevails (Ethiopia Stands / ኢትዮጵያ ትቅደም)", explanation: "'Ethiopia Prevails' (Ethiopia Tikdem) reflects the national spirit of resilience and sovereignty. Ethiopia is one of only two African nations never fully colonized." },
  { question: "What is the Amharic word for Ethiopia?", answer: "ኢትዮጵያ (Ityop'iya)", explanation: "In Amharic, Ethiopia is written as ኢትዮጵያ. The country is also historically called 'Abyssinia', derived from the Habesha people's name for themselves." },
  { question: "How many languages are estimated to be spoken in Ethiopia?", answer: "Over 80 languages", explanation: "Ethiopia is one of the world's most linguistically diverse countries, with over 80 distinct languages belonging to Afroasiatic (Semitic, Cushitic, Omotic) and Nilo-Saharan families." },
  { question: "What is the total approximate population of Ethiopia?", answer: "Over 120 million people", explanation: "Ethiopia is the second most populous country in Africa after Nigeria, with a population exceeding 120 million people as of recent estimates." },
  { question: "What is the currency of Ethiopia?", answer: "Ethiopian Birr (ETB)", explanation: "The Ethiopian Birr is the official currency. 'Birr' means 'silver' in Amharic. It has been the country's currency since 1945, replacing the Maria Theresa Thaler." },
  { question: "Which Ethiopian emperor was coronated in 1930 and reigned until 1974?", answer: "Emperor Haile Selassie I", explanation: "Haile Selassie (born Tafari Makonnen) was crowned Emperor in 1930. He modernized Ethiopia, led it into the League of Nations and founded the OAU before being deposed by the Derg in 1974." },
  { question: "What is the primary system of government in Ethiopia today?", answer: "Federal Democratic Republic", explanation: "Ethiopia is officially the Federal Democratic Republic of Ethiopia (FDRE), a federal state made up of 12 regional states and 2 chartered cities." },
];

// Fisher-Yates shuffle for truly random question order
function shuffleTrivia(pool: CulturalTrivia[]): CulturalTrivia[] {
  const arr = [...pool];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// Track used indices to avoid repeating the same question
let shuffledPool: CulturalTrivia[] = [];
let poolIndex = 0;

export function getNextTrivia(): CulturalTrivia {
  if (poolIndex >= shuffledPool.length) {
    shuffledPool = shuffleTrivia(RAW_TRIVIA_POOL);
    poolIndex = 0;
  }
  return shuffledPool[poolIndex++];
}
